### ISSUE TITLE
Add "Developer mode" setting to enable showing additional info about chats and users

### ISSUE THREAD

**Issue by ggoraa** [mock-foundation/moc#124]
Exact info that will be seen with this setting enabled:
- User ID
- Chat ID
- A DC (data center) on which the user is, like DC2

It would pretty useful for devs, because they will not need to fiddle with bots in any way to get info listed above, and normal users are also not confused because this setting will be off by default.

Can be done with Stage 2 but I think I would drop this to Stage 3

**Comment by ggoraa** [comment]
Nope, doing it with #122

**Comment by ggoraa** [comment]
Btw, no DC data will be implemented, its not available in TDLib and is basically useless

**Comment by c-h3xcode** [comment]
@ggoraa как это not available?

**Comment by ggoraa** [comment]
Implemented in #122
